Convert plugin to support Girder 3
ImageMarkup/isic_challenge_submission pull request #16
Opened 2018-11-06 14:56 UTC by danlamanna

2018-11-07 02:08 UTC, brianhelba commented on girder_isic_challenge_submission/web_client/package.json
> +    "name": "@girder/girder_isic_challenge_submission",
Even though this is unpublished, I don't think we should consider this under the `@girder` npm namespace.

2018-11-07 02:09 UTC, brianhelba commented on setup.py
> +    name='girder-isic-challenge-submission',
Although this is a Girder plugin, it lives under the ISIC project, so I think we should drop the prefix `girder` from this package's name everywhere.

2018-11-07 02:10 UTC, brianhelba commented on tox.ini
> +[testenv:lint]
Since we have testing now, could you add a small CircleCI config file to run it?

2018-11-07 02:11 UTC, brianhelba requested changes
Some comments inline.

2018-11-07 02:13 UTC, danlamanna commented on setup.py
> +    name='girder-isic-challenge-submission',
@jbeezley smh

2018-11-07 02:21 UTC, brianhelba commented on setup.py
> +    name='girder-isic-challenge-submission',
@danlamanna Can you elaborate? Is there a naming convention here already?

2018-11-07 14:58 UTC, danlamanna commented on tox.ini
> +[testenv:lint]
I added linting and testing for py27 and py36. I'll added py37 when a new alpha is cut on Girder.

Do we even want to bother testing Python 2?

2018-11-07 15:00 UTC, danlamanna commented on setup.py
> +    name='girder-isic-challenge-submission',
Naming is particularly tricky with Girder 3 plugins, there are several different names to wrangle so I went through quite a bit of trouble to get the `girder-` working. I think it's useful to know which of our packages are Girder plugins just from the name, despite them not being official Girder plugins. Is there someway we could denote that otherwise?

2018-11-07 15:05 UTC, danlamanna commented on girder_isic_challenge_submission/web_client/package.json
> +    "name": "@girder/girder_isic_challenge_submission",
Should we create a namespace for ISIC now or in the future?

2018-11-08 20:26 UTC, danlamanna commented
@brianhelba ready for review again

2018-11-13 18:58 UTC, brianhelba approved these changes

2018-11-13 18:59 UTC, merged