Throttle submissions
ImageMarkup/isic_challenge_submission pull request #17
Opened 2018-11-07 01:55 UTC by danlamanna

Depends on #16, only https://github.com/ImageMarkup/isic_challenge_submission/commit/2c9ee7798c58c2a912e43e74e38784e5a4cfb5c1 is relevant here.

Still needs UI portion.

2018-11-07 02:20 UTC, brianhelba requested changes
Some inline feedback.

I think it makes sense to put the UI changes into this PR too.

2018-11-07 02:20 UTC, brianhelba commented on girder_isic_challenge_submission/__init__.py
> +        phase = Phase().load(id=event.info['params']['phaseId'], user=user)
What if `phaseId` exists but is invalid, so `phase` is `None`?

2018-11-07 02:20 UTC, brianhelba commented on girder_isic_challenge_submission/__init__.py
> +            '$and': [
From [MongoDB docs on `$and`](https://docs.mongodb.com/manual/reference/operator/query/and/):
> MongoDB provides an implicit AND operation when specifying a comma separated list of expressions. Using an explicit AND with the $and operator is necessary when the same field or operator has to be specified in multiple expressions.

You can just provide a dict with `creatorId` and `created` keys.

2018-11-07 02:20 UTC, brianhelba commented on girder_isic_challenge_submission/__init__.py
> +                        '$eq': user['_id']
From [MongoDB docs on `$eq`](https://docs.mongodb.com/manual/reference/operator/query/eq/):
> The $eq expression is equivalent to `{ field: <value> }`.

You can just have `'creatorId': user['_id']`

2018-11-07 02:20 UTC, brianhelba commented on girder_isic_challenge_submission/__init__.py
> +        submissions_in_past_week = Submission().getAllSubmissions(phase, filter={
The rest of this code uses camelCase. Also, can you name it slightly more generally, in case we change the time period later.

2018-11-07 02:20 UTC, brianhelba commented on girder_isic_challenge_submission/__init__.py
> +                        '$gte': datetime.utcnow() - timedelta(weeks=1)
Can you extract this `timedelta` up to a variable at the top of the function? It's likely we'll want to tweak it over time, and it's easier to spot up there (admittedly, this isn't a particularly complicated function).

2018-11-07 17:33 UTC, danlamanna commented
Added UI

2018-11-08 20:27 UTC, danlamanna commented
@brianhelba ready for review again

(Still looking into failed submissions)

2018-11-12 15:51 UTC, danlamanna commented
@brianhelba ready for review forreal.

2018-11-13 23:11 UTC, brianhelba approved these changes

2018-11-13 23:12 UTC, merged