Enforce the three approach per phase limit on the submission form
ImageMarkup/isic_challenge_submission pull request #4
Opened 2018-07-16 19:35 UTC by jbeezley

This is pretty straightforward... just added some text and disabled the "create new approach" button when there are more than two existing approaches.

![test](https://user-images.githubusercontent.com/31890/42779116-6d78dd98-890d-11e8-9251-f2fab4e64df5.png)

2018-07-16 19:57 UTC, msmolens commented
The functionality looks good. A couple notes:
- Should we restrict the behavior to test ("final") phases?
- The first sentence of the note could read "You may submit up to three approaches per task." "Phase" is an internal term.

2018-07-17 15:09 UTC, msmolens requested changes

2018-07-17 15:09 UTC, msmolens commented on web_client/wrapSubmitView.js
>              this.createNewApproach = true;
There is a race condition that can break the submission limit functionality. When initializing the view there are two fetch requests:
- the fetch of approaches (in `SubmitView.initialize()`), and
- the fetch of the most recent submission (in `setDefaultsFromApproach()`)

The `render` function is called when each request completes. When the second fetch completes first, `this.createNewApproach` is set to true. At that point, even if `render` is called again, the user is allowed to submit a new approach despite possibly being over the limit.

2018-07-17 16:26 UTC, jbeezley commented on web_client/wrapSubmitView.js
>              this.createNewApproach = true;
I resolved the race condition, but there is still the condition when the approaches endpoint fails or is slow that the user *could* submit a new approach.  The only way to avoid that would be to go into covalic and defer the original render until after the approach fetching resolves.

2018-07-17 17:15 UTC, msmolens approved these changes

2018-07-17 17:18 UTC, merged